name: 'Terraform-plan'

on:
  push:
    branches: 
      - "development"
      - "feature/*"  # This will trigger on any feature branch
  pull_request:
    branches:
      - "development"

permissions:
  contents: read
  id-token: 'write'

jobs:
  terraform:
    name: 'Terraform plan'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - id: auth
      uses: google-github-actions/auth@v2.0.0
      with:
        workload_identity_provider: 'projects/899750260822/locations/global/workloadIdentityPools/new-github-workload-pool/providers/my-github'
        service_account: 'github-actions-sa@cicd-project-435214.iam.gserviceaccount.com'

    - name: Terraform Init
      run: terraform init

    # Generates an execution plan for Terraform
    - name: Terraform Plan
      run: terraform plan -input=false
