name: VPC Plan

on:
  push:
    branches:
      - development
    paths:
      - './module/vpc/**'
      - './**'

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2.0.0
        with:
          service_account: 'github-actions-sa@your-project.iam.gserviceaccount.com'

      - name: Initialize Terraform
        run: terraform init
        working-directory: ./module/vpc

      - name: Terraform Plan
        run: terraform plan -input=false
        working-directory: ./module/vpc
